<?php

function sherlock_menu() {
    $items = array();
    $items['sherlock'] = array(
        'title' => 'Search Query Constructor',
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('sherlock_searchform'),
        'access callback' => TRUE,
    );

    return $items;
}

function sherlock_searchform($form, &$form_state) {
    $form['#tree'] = TRUE;
    $form['#prefix'] = '<div id="sherlock-search-form">';
    $form['#suffix'] = '</div>';

    foreach ($form_state['user_added'] as $key => $value) {
        $form[$key] = $value;
    }

    $form['btn_addfield'] = array(
        '#type' => 'submit',
        '#value' => 'Add Term',
        '#name' => 'btn_addfield',
        '#submit' => array(
            'btn_addfield_handler',
        ),
        '#ajax' => array(
            'callback' => 'updatedform_return',
        ),
    );

    $form['btn_addblock'] = array(
        '#type' => 'submit',
        '#value' => 'Add Term Variations',
        '#name' => 'btn_addblock',
        '#submit' => array(
            'btn_addblock_handler',
        ),
        '#ajax' => array(
            'callback' => 'updatedform_return',
        ),
    );

    $form['btn_submit'] = array(
        '#type' => 'submit',
        '#value' => 'Save',
        '#name' => 'btn_submit',
    );

    $form['btn_reset'] = array(
        '#type' => 'submit',
        '#value' => 'Reset Form',
        '#name' => 'btn_reset',
        '#submit' => array(
            'btn_reset_handler',
        ),
    );

    return $form;
}

function updatedform_return($form, $form_state) {
    $commands = array();
    $commands[] = ajax_command_replace('#sherlock-search-form', drupal_render($form));
    return array(
        '#type' => 'ajax',
        '#commands' => $commands,
    );
}

function btn_addfield_handler($form, &$form_state) {
    $pressed_btn_name = $form_state['triggering_element']['#name'];
    if ($pressed_btn_name != 'btn_addfield') {return;}

    $num_elements = get_num_elements($form_state);

    //'E-' is for Element
    $form_state['user_added']['E-'.$num_elements] = array(
        '#title' => 'E-'.$num_elements,
        '#type' => 'textfield',
        '#required' => TRUE,
    );

    $form_state['rebuild'] = TRUE;
}

function btn_addblock_handler($form, &$form_state) {
    $pressed_btn_name = $form_state['triggering_element']['#name'];
    if ($pressed_btn_name != 'btn_addblock') {return;}

    $num_elements = get_num_elements($form_state);

    //'B-' is for Block
    $form_state['user_added']['B-'.$num_elements] = array(
        '#type' => 'fieldset',
        '#title' => 'B-'.$num_elements,
        '#collapsible' => FALSE,
        '#collapsed' => FALSE,
    );

    //This is nested block for variation values only
    $form_state['user_added']['B-'.$num_elements]['VALUES'] = array(
        '#type' => 'fieldset',
        '#collapsible' => FALSE,
        '#collapsed' => FALSE,
    );

    $form_state['user_added']['B-'.$num_elements]['btn_addvariation-'.$num_elements] = array(
        '#type' => 'submit',
        '#value' => 'Add Variation',
        '#name' => 'btn_addvariation-'.$num_elements,
        '#submit' => array(
            'btn_addvariation_handler',
        ),
        '#ajax' => array(
            'callback' => 'updatedform_return',
        ),
    );

    $form_state['rebuild'] = TRUE;
}

function btn_addvariation_handler($form, &$form_state) {
    $pressed_btn_name = $form_state['triggering_element']['#name'];
    if (!((bool) strstr($pressed_btn_name, 'btn_addvariation'))) {return;}

    $btn_id = (int) explode('-', $pressed_btn_name)[1];
    $variationNo = isset($form_state['values']['B-'.$btn_id]['VALUES']) ? count($form_state['values']['B-'.$btn_id]['VALUES']) : 0;
    $newfield = array(
        '#type' => 'textfield',
        '#required' => TRUE,
        '#title' => 'Variation '.$btn_id.'/'.$variationNo,
    );

    array_push($form_state['user_added']['B-'.$btn_id]['VALUES'], $newfield);

    $form_state['rebuild'] = TRUE;
}

function btn_reset_handler($form, &$form_state) {
    $pressed_btn_name = $form_state['triggering_element']['#name'];
    if ($pressed_btn_name != 'btn_reset') {return;}

    unset ($form_state['user_added']);
    $form_state['rebuild'] = TRUE;
}

function sherlock_searchform_submit($form, &$form_state) {
    //Don't forget to check pressed button!
    sherlock_debug_msg($form_state['values']);
}

function get_num_elements(&$form_state) {
    if (!isset($form_state['user_added'])) {
        $form_state['user_added'] = array();
        return 0;
    } else {
        return count($form_state['user_added']);
    }
}

function sherlock_debug_msg($x) {
    drupal_set_message('<pre>'.print_r($x, true).'</pre>');
}