<?php
require_once 'fleamarket_classes.php';
require_once 'sherlock_core_functions.php';

define('OLX_NAME', OlxMarket::getMarketName());
define('OLX_URL', OlxMarket::getBaseURL());
define('BESPLATKA_NAME', BesplatkaMarket::getMarketName());
define('BESPLATKA_URL', BesplatkaMarket::getBaseURL());
define('SKYLOTS_NAME', SkylotsMarket::getMarketName());
define('SKYLOTS_URL', SkylotsMarket::getBaseURL());

function sherlock_menu() {
  $items = array();

  $items['sherlock'] = array(
    'title' => 'Sherlock - Fleamarket Digger.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sherlock_searchform'),
    'access callback' => TRUE,
  );

  $items['get_demo_content'] = array(
    'title' => 'Get demo content',
    'page callback' => 'get_demo_content_ajax',
    'delivery callback' => 'ajax_deliver',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );

  return $items;
}

function sherlock_searchform($form, &$form_state) {
  //If form is just created -> we will be on the first step. If user already explored the form -> get current step.
  $step = (isset($form_state['storage']['step']) && !empty($form_state['storage']['step'])) ? intval($form_state['storage']['step']) : 1;

  $form['#tree'] = TRUE;
  $form['#prefix'] = '<div id="sherlock-search-form">';
  $form['#suffix'] = '</div>';

  $form['current-step-title-wrapper'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array('current-step-title-wrapper'),
    ),
  );

  $form['current-step-title-wrapper']['title'] = array(
    '#markup' => '<h3>'.get_form_title($step).'</h3>',
  );

  //Depending on which step we are on, show corresponding part of the form:
  switch ($step) {
    //Show part of the form for step 1:
    case 1:
      //Print out supported flea-markets. TODO: maybe this output better to do with theme function and template file?
      $formatted_list = array();

      $formatted_list[OLX_NAME] = OLX_NAME . ' [<a target="_blank" href="' . OLX_URL . '">' . t('Open this market\' website in new tab') . '</a>]';
      $formatted_list[BESPLATKA_NAME] = BESPLATKA_NAME . ' [<a target="_blank" href="' . BESPLATKA_URL . '">' . t('Open this market\' website in new tab') . '</a>]';
      $formatted_list[SKYLOTS_NAME] = SKYLOTS_NAME . ' [<a target="_blank" href="' . SKYLOTS_URL . '">' . t('Open this market\' website in new tab') . '</a>]';

      $form['resources_chooser'] = array(
        '#type' => 'checkboxes',
        '#options' => $formatted_list,
        '#title' => 'Choose flea-markets websites to search on',
      );

      $form['query_constructor_block'] = array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array('query_constructor_block'),
        ),
      );

      //Don't try to combine next two IFs to one block, they need to be as they written!:
      //The first:
      if(!isset($form_state['user_added'])) {
        new_block($form_state);
      }

      //The second:
      if(isset($form_state['user_added'])) {
        foreach ($form_state['user_added'] as $key => $value) {
          $form['query_constructor_block'][$key] = $value;
        }
      }

      //By default, search performs only in headers, but some resources (OLX and Skylots, but not Besplatka) also supports
      //search in body. Technically, it adds specific suffix to URL.
      $form['dscr_chk'] = array(
        '#type' => 'checkbox',
        '#title' => 'Search not only in titles, but in descriptions too (if resource supports).',
      );

      //Create a DIV wrapper for button(s) - according to Drupal 7 best practices recommendations:
      $form['first_step_buttons_wrapper'] = array('#type' => 'actions');

      //...and three main controls buttons () in this wrapper:
      $form['first_step_buttons_wrapper']['btn_addterm'] = array(
        '#type' => 'submit',
        '#value' => 'Add Term',
        '#name' => 'btn_addterm',
        '#submit' => array(
          'btn_addterm_handler',
        ),
        '#ajax' => array(
          'callback' => 'updatedform_return',
        ),
      );

      $form['first_step_buttons_wrapper']['btn_preview'] = array(
        '#type' => 'submit',
        '#value' => 'Preview Results',
        '#name' => 'btn_preview',
        '#validate' => array(
          'btn_preview_validate_handler'
        ),
        '#submit' => array(
          'btn_preview_handler',
        ),
      );

      $form['first_step_buttons_wrapper']['btn_reset'] = array(
        '#type' => 'submit',
        '#value' => 'Reset All',
        '#name' => 'btn_reset',
        '#limit_validation_errors' => array(), //We don't want validate any errors for this submit button, because this is RESET button!
        '#submit' => array(
          'btn_reset_handler',
        ),
      );

      break;

    //Show part of the form for step 2:
    case 2:
      //At first, plug in jQuery AJAX additions for this part of the form:
      $form['#attached']['js'] = array(
        drupal_get_path('module', 'sherlock') . '/ajax_content_request.js',
      );

      //Second, attach drupal.ajax library, this is the same as do it by function: drupal_add_library('system', 'drupal.ajax');
      $form['#attached']['library'] = array(
        array('system', 'drupal.ajax')
      );

      $form['#attached']['css'] = [
        drupal_get_path('module', 'sherlock') . '/templates/content_output_tabs.css',
      ];

      //drupal_add_library('system', 'drupal.ajax');
      //drupal_add_library('system', 'jquery.form');

      $output_containers = [];
      foreach ($form_state['values']['resources_chooser'] as $key => $value) {
        //Let's create div-container for every checked resource, because we need place where to output parse result
        if ($value !== 0) {
          $output_containers[$key]['container_title'] = $value;
          $output_containers[$key]['container_id'] = strtolower($value).'-output-block';
        }
      }

      $form['preview_results_area'] = array(
        '#type' => 'markup',
        '#markup' => theme('preview_results', array('output_containers' => $output_containers)),
        '#prefix' => '<div id="preview-results-parent-block">',
        '#suffix' => '</div>',
      );

      break;
  }

  return $form;
}

function get_demo_content_ajax() {
  $commands[] = ajax_command_append('#olx-output-block', '<p>Hello there!</p>');
  return array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );
}

//========================================= HANDLERS FOR ALL FORM BUTTONS ==============================================

function btn_addterm_handler($form, &$form_state) {
  $pressed_btn_name = $form_state['triggering_element']['#name'];
  if ($pressed_btn_name != 'btn_addterm') {return;}

  new_block($form_state);

  $form_state['rebuild'] = TRUE;
}

function btn_addvariation_handler($form, &$form_state) {
  $pressed_btn_name = $form_state['triggering_element']['#name'];
  if (!((bool) strstr($pressed_btn_name, 'btn_addvariation'))) {return;}

  $btn_id = (int) explode('-', $pressed_btn_name)[1];
  $variationNo = isset($form_state['values']['query_constructor_block']['KEYWORD-'.$btn_id]['VALUES']) ? count($form_state['values']['query_constructor_block']['KEYWORD-'.$btn_id]['VALUES']) : 0;
  $newfield = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => 'Variation '.$btn_id.'/'.$variationNo,
  );

  array_push($form_state['user_added']['KEYWORD-'.$btn_id]['VALUES'], $newfield);

  $form_state['rebuild'] = TRUE;
}

function btn_reset_handler($form, &$form_state) {
  $pressed_btn_name = $form_state['triggering_element']['#name'];
  if ($pressed_btn_name != 'btn_reset') {return;}

  unset ($form_state['user_added']);
  $form_state['rebuild'] = FALSE;
}

function btn_preview_validate_handler($form, &$form_state) {
  $resources = $form_state['values']['resources_chooser'];
  $some_resources_selected = FALSE;
  foreach ($resources as $value) {
    if ($value !== 0) {
      $some_resources_selected = TRUE;
      break;
    }
  }
  if (!$some_resources_selected) {
    form_set_error('resources_chooser', 'Please, select at least one resource where to search.');
  }
}

function btn_preview_handler($form, &$form_state) {
  $pressed_btn_name = $form_state['triggering_element']['#name'];
  if ($pressed_btn_name != 'btn_preview') {return;}

  //Get flag which indicates - search title only or body too:
  $check_description_too = ((int) $form_state['values']['dscr_chk']) === 0 ? FALSE : TRUE;

  //Save all block values\variations to separate array
  $block_values = array();
  foreach ($form_state['values']['query_constructor_block'] as $key => $value) {
    if (startsWith($key, 'KEYWORD-')) {
      $block_values[] = $value['VALUES']; //Each value of $block_values is ARRAY with combinations of one given keyword (like sony, soni).
    }
  }

  //Now let's build list of all resources and their settings. Settings we can get as corresponding class static properties.
  $resources_list = array();
  $resources_list[OLX_NAME] = new OlxMarket();
  $resources_list[BESPLATKA_NAME] = new BesplatkaMarket();
  $resources_list[SKYLOTS_NAME] = new SkylotsMarket();

  //Array with all search URLs for all user-specified resources. This collection of URL we will use to cURL each of them at the next step.
  //All values are splitted by nested arrays. Keys to nested arrays are names of the resources.
  $constructed_urls_collection = array();

  foreach ($form_state['values']['resources_chooser'] as $key => $value) { //$key here is flea market name, like OLX, Besplatka, SkyLots
    if ($value !== 0) { //we take into consideration only checked resources, if checkbox unchecked its value == 0
      $prefix = $resources_list[$key]::getSearchURL();
      $glue = $resources_list[$key]::getWordsGlue();
      $suffix = $check_description_too ? $resources_list[$key]::getSuffixDescrChk() : '';
      $constructed_urls_collection[$key] = generate_all_possible_strings($block_values, $prefix, $glue, $suffix);
    }
  }

  $form_state['constructed_urls_collection'] = $constructed_urls_collection;
  //$form_state['redirect'] = 'sherlock/preview-results';
  $form_state['storage']['step'] = 2;
  $form_state['rebuild'] = TRUE;
}

//========================================= OTHERS FORM ROUTINE FUNCTIONS ==============================================

function new_block(&$form_state) {
  $num_elements = isset($form_state['user_added']) ? count($form_state['user_added']) : 0;

  $form_state['user_added']['KEYWORD-'.$num_elements] = array(
    '#type' => 'fieldset',
    '#title' => 'KEYWORD-'.$num_elements,
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );

  //This is nested block\container for variation values only (with a view to separate values from button)
  $form_state['user_added']['KEYWORD-'.$num_elements]['VALUES'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );

  $form_state['user_added']['KEYWORD-'.$num_elements]['VALUES'][0] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => 'Variation '.$num_elements.'/'.'0',
  );

  //Create new DIV wrapper for Add Variation button (according to Drupal 7 best practices recommendations):
  $form_state['user_added']['KEYWORD-'.$num_elements]['add_variation_button_wrapper'] = array('#type' => 'actions');

  //...and new button inside this wrapper:
  $form_state['user_added']['KEYWORD-'.$num_elements]['add_variation_button_wrapper']['btn_addvariation-'.$num_elements] = array(
    '#type' => 'submit',
    '#value' => 'Add Variation',
    '#name' => 'btn_addvariation-'.$num_elements,
    '#submit' => array(
      'btn_addvariation_handler',
    ),
    '#ajax' => array(
      'callback' => 'updatedform_return',
    ),
  );
}

function updatedform_return($form, $form_state) {
  $commands = array();
  $commands[] = ajax_command_replace('#sherlock-search-form', drupal_render($form));
  return array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );
}

//We have a multistep form, so we need different titles for every step. This function returns title depends on current step:
function get_form_title(int $step) {
  $title = '';
  switch ($step) {
    case 1:
      $title = 'Step 1: Make a search query.';
      break;

    case 2:
      $title = 'Step 2: Preview results.';
      break;

    default:
      $title = 'No title for this step.';
  }

  return $title;
}

/**
 * Implements hook_theme().
 */
function sherlock_theme($existing, $type, $theme, $path) {
  return array(
    'preview_results' => array(
      'variables' => array(
        'output_containers' => NULL,
      ),
      'template' => 'sherlock_preview_results',
      'path' => drupal_get_path('module', 'sherlock') . '/templates',
    ),
  );
}
